language: node_js
node_js:
 - "8.9.1"
script:
 - npm test
after_success:
  - npm run coveralls
  - npm run coverage
  - npm run report-coverage
  - CODECLIMATE_REPO_TOKEN=5159bbd9627a63605af627b84b529d587d143c5f145b133c442e2b8d5a11f79a codeclimate-test-reporter < ./coverage/lcov.info
  